name: Deploy HoneyCloud to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'honeycloud/**'      # Only trigger if backend code changes
      - 'docker-compose.yml' # Only trigger if docker config changes
      - 'requirements.txt'   # Only trigger if dependencies change
      - '.github/workflows/deploy.yml'
      - 'api/**'
      - 'layer2/**'
      - 'cowrie/**'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            cd ~/honeycloud

            # --- GITOPS FIX: Clean up Docker's fake folder ---
            sudo docker compose down cowrie
            sudo rm -rf cowrie/cowrie.cfg
            #-----------------------------------
            git pull origin main
            sudo docker compose up --build -d
            sudo docker image prune -a -f